### ISSUE TITLE
Building for x64 on Windows

### ISSUE THREAD

**Issue by dgalaktionov** [yamashi/DestroyerOfWorlds#5]
I am still unable to build for x64 with MSVC 2017 because of the sanity check `static_assert(alignof(T) <= alignof(std::max_align_t))` in `Allocator.h`.

It turns out that cryptopp decides to align some internal `XChaCha20` element (I think the one declared in `secblock.h` , if you are curious) to 16 bytes since it correctly determines that my alloc'ed addresses are 16 aligned because it's a x64 machine ( `_M_X64` is defined). However, `alignof(std::max_align_t)` stubbornly stays at 8, thus making it fail to build, although it builds fine on GCC where `alignof(std::max_align_t)` is 16.

Not knowing what to believe, I've executed thousands of `malloc(1)` and all the addresses turn out 16 aligned when building for x64, so if I remove the assert then everything works. It looks like, even though `std::max_align_t` may be wrong, [it is safe to assume that malloc addresses are 16 aligned in x64](https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=vs-2019).

So based on these findings, my proposals are:

- Define an alternative `max_align_t` based on the detected architecture.
- Alternatively, or if you want the allocator to **additionally** support super-alignment, implement a second version of `StandardAllocator::Allocate` that would make use of `std::align`, not unlike the one exposed [here](https://stackoverflow.com/a/17380899). This trick introduces a header of `size_t` and as many wasted bytes as the alignment requires, so the types that don't require super-alignment would be still allocated with the old method.

At first I've considered using `new` instead of `malloc`, as it seems to respect the required alignment for the type in MSVC, but it turned out that it doesn't in GCC and [they don't seem to be in much hurry to fix that](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=15795).

**Comment by maximegmd** [comment]
This should be fixed now,  good catch !
